### ISSUE TITLE
Unable to size properly

### ISSUE THREAD

**Issue by schutzie** [Learus/react-material-ui-carousel#100]
I'm not able to size the carousel quite the way I want.  Not an "issue" with the project I suppose, but not sure where else to ask.  I'm using the className prop, just not sure what styles to assign to the class to give a maximum width, maximum height, and to maintain aspect ratio.  Has anyone come up with best practices for this particular component?

* Provide a maximum width (either in explicit pixels or based on the theme like xs, sm, etc.)
* Provide a maximum height
* All images in the carousel retain original ratio but do not exceed width/height above

Thank you!

**Comment by Learus** [comment]
Hello and sorry for the late response.

As you're mentioning this is not an issue with this library, so I will be closing this issue.

I urge you to check the [demo code](https://github.com/Learus/react-material-ui-carousel/tree/master/demo) for an example of how to use the library if you haven't already figured out a solution. It's a simple CRA app that uses MUI. I think it will help that specific problem since it's using simple SCSS to style and size the carousel items.

Feel free to ask if you still have questions.
