### ISSUE TITLE
Direction of Slide transition

### ISSUE THREAD

**Issue by sahuam** [Learus/react-material-ui-carousel#108]
I am trying to build a carousel where the slide will move as same as the directions in demo.
https://learus.github.io/react-material-ui-carousel/

example : in auto play mode, for all slides the direction of transition is right to left.  

Issue : Now when I use the same demo project to test. The slides are moving from right to left, But at the end of the slide (the last slide) when it moves to the 1st slide the direction changes (reverts) to left to right !!

Is there any way we can provide the direction for slide effect using props? 

-------edited-------
Currently, for the Slide direction is given as below : 
direction={props.active ? (props.isNext ? "left" : "right") : (props.isNext ? "right" : "left")}

But will it be possible to provide the below one through any carousel props.:
direction={props.active ?  "left" : "right"} ---> this is resolving the issue for us!!

**Comment by Learus** [comment]
There is a new prop in version `v2.3.0` called `reverseEdgeAnimationDirection` that is set to `true` by default.

This is the current functionality, a.k.a when the carousel reaches its end and tries to cycle it goes back to the start using the "back" animation. Reverse that for when the carousel is on its first child and tries to go to the last.

Setting this prop to false disables this functionality. Every "next" action uses the forward animation (right to left) and every "previous" action uses the back animation (left to right).

Of course, this only applies to the `slide` animation, since the `fade` animation has no direction.

I hope this solution solves the problem for you.
