### ISSUE TITLE
How to trigger next() from within an item

### ISSUE THREAD

**Issue by avianheit07** [Learus/react-material-ui-carousel#114]
Is it possible to trigger the next() method from within a carousel item instead of triggering it when clicking the default navButton? In my design, there is a next button inside each item which behaves exactly like the next navButton.

**Comment by Learus** [comment]
Hello.

Firstly, I urge you to try and customize the already existing nav buttons to achieve what you want, because the solution explained below introduces plenty of problems. **There is no clean way to do this as of the time of writing.**

However, you could try to implement it as follows:

1. Disable autoPlay `autPlay={false}`
2. Make the navButtons invisible `navButtonsAlwaysInvisible={false}`
3. Disable the indicators `indicators={false}`
3. Create a stateful number that handles indexing.
4. Set that value to the index prop `index={myStatefulIndex}`
5. Make your buttons handle the stateful value in their `onClick` methods

This is a workaround to make this work, but it does effectively rerender the carousel on every state change. That means that animations don't work. In addition you have to disable navButtons and indicators, since it will introduce breaking complexity of indexing while the carousel is cycling.

Use at your own discretion.
