### ISSUE TITLE
[Feature Request] Multiple slides

### ISSUE THREAD

**Issue by troyschneringer** [Learus/react-material-ui-carousel#146]
It would be great to have the ability to show more than one slide at a time:

```
<Carousel visibleSlides={3} ... />
```

**Comment by Learus** [comment]
Hello there.

You can achieve the wanted functionality by changing the structure of the children you're putting inside the Carousel. Let's say the structure right now is as follows:

```tsx
<Carousel>
    <div>Slide 1</div>
<div>Slide 1</div>
<div>Slide 1</div>
</Carousel>
```

**Comment by Learus** [comment]
I think it would be too hard and would go against the library's core values to implement such a feature.

If I were to do it, I can't think of any way to discern how the styling should be.
Where should the extra slides render? Below? On the side?

The above solution works, exactly because you can style your "wrapper" elements however you believe they should look.

Do you have any ideas?

**Comment by marciojuniors2** [comment]
it is interesting to assume that most of the time, people will make a map in this structure, so this model would not be valid...

```

<Carousel>
        {
        items.map( (item) => (
            <div>
                <div key={item.id} ..etc  >Slide 1</div>
                <div key={item.id} ...etc >Slide 2</div>
            </div>
          ))
        }
</Carousel>

this way we would have duplicates etc... how do we proceed?

```
