### ISSUE TITLE
return statement needed inside the map function in order to show the paper

### ISSUE THREAD

**Issue by Radikad** [Learus/react-material-ui-carousel#19]
I've used this a few hours ago with nextjs and I couldn't get the paper without putting return like this. So I would like to inform this for your references. Thank you. Also would like to say that this library is super cool. 

```
<Carousel animation="slide">
        {items.map((item, key) => {
          return (
            <div key={key}>
              <Item item={item} />
            </div>
          );
        })}
      </Carousel>
```

**Comment by Learus** [comment]
Hello there. Thank you for the kind words.

Could you elaborate on what you tried, and what your error was?

Did you try something like this:
```js
<Carousel animation="slide">
    {items.map( (item, key) => <Item key={key} item={item}/>) }
</Carousel>
```
and it didn't work?
What exactly do you mean, you "couldn't get the paper without putting return"?

**Comment by Radikad** [comment]
Thank you for the reply. Actually what I did was, I've used the code in the documentation like below
image 1 shows that code that I've used. and the image 2 show the output that I've got. only 2 indicators. not the paper. 


` <Carousel>
            {
                items.map( item => {
                    <Item item={item} />
                })
            }
        </Carousel>`

Image 1
![Screenshot 2020-05-15 at 10 59 36](https://user-images.githubusercontent.com/53252395/82014918-39ada500-969b-11ea-8bcf-599ef3231cc1.png)

image 2 (output)
![Screenshot 2020-05-15 at 11 02 59](https://user-images.githubusercontent.com/53252395/82015133-ac1e8500-969b-11ea-88b1-73104a37013b.png)


then I've changed the code like below 

`<Carousel animation="slide">
        {items.map((item, key) => {
          return (
            <div key={key}>
              <Item item={item} />
            </div>
          );
        })}
      </Carousel>`

then I've got the below output 
![Screenshot 2020-05-15 at 11 05 49](https://user-images.githubusercontent.com/53252395/82015336-23541900-969c-11ea-8c5e-d48b3bb01e6d.png)

I hope you could get it now. :)

**Comment by Learus** [comment]
Yes i see, this is not how .map callbacks work. There is a typo in the documentation code, and I hadn't noticed it. The curly braces must be removed. I'm so sorry.

You can't have a map callback like this 
```js
array.map( item => { <JSXElement prop={item}/> })
```
since the .map callback needs to return something.

If you **don't** put braces around the return expression the "return" is implied and you doesn't have to exist
```js
array.map( item => <JSXElement prop={item}/> );
```
If you **do** put braces around it though it actually does not return anything, and you get no output as in your case.

Check the [map documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) for more info on the matter.

I will correct the typo on my documentation asap
