### ISSUE TITLE
CSS equivalent

### ISSUE THREAD

**Issue by KevinBurton** [Learus/react-material-ui-carousel#42]
I am trying to get the sample up an running and it turns out the scss file with the demo doesn't seem to parse right. Rather than go down the rabbit hole of figuring out what the problem is, would it be possible to get the equivalent CSS file? I just want to get the demo up and running. The scss file goes with this [sample ](https://github.com/Learus/react-material-ui-carousel/blob/master/demo/src/components/Example.js). This is the specific [file](https://github.com/Learus/react-material-ui-carousel/blob/master/demo/src/style/Example.scss).

**Comment by Learus** [comment]
Hello.
You can use any SCSS -> CSS transpiler, to get the equivalent CSS file. [This one](https://jsonformatter.org/scss-to-css) for example.

However, I would like to go down the rabbit hole of figuring out what the problem is. So I'll ask a couple of questions:
* Is `node-sass` installed?
* What do you mean it "doesn't parse right exactly?

**Comment by KevinBurton** [comment]
This one says there is an error in the SCCS.

**Comment by Learus** [comment]
There is an error in the SCSS because I'm importing some coloration and font-size variables from another file I'm calling `global.scss`. If you want to have an exact equivalent CSS file you will have to hard-code those variables in the CSS.

Moreover, you have not answered the questions in my previous response.
Did you try installing `node-sass`? (`npm install node-sass`) Also, try to clone the repo again and `npm install`. Maybe it will work after the latest updates I did.

**Comment by KevinBurton** [comment]
Thank you for your email. I have installed node-sass. I think the problem
was I didn’t have global.scss. I think the issue is resolved now. It was
just my unfamiliarity with SCSS that triggered this issue.

**Comment by Learus** [comment]
Great! I am glad it's resolved.
