### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by KevinBurton** [Learus/react-material-ui-carousel#44]
Every once and a while. I am assuming when I unmount the carousel during a repaint. I get the following warning message:

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Carousel (created by WithStyles(Carousel))
    in WithStyles(Carousel) (at CarouselBanner.jsx:197)
    in div (at CarouselBanner.jsx:196)
    in CarouselBanner (created by Context.Consumer)
    in withRouter(CarouselBanner) (at Dashboard.js:6)
    in Dashboard (created by Context.Consumer)
    in Route (at Public.js:27)

```
Maybe there needs to be some cleanup when the component unmounts?

**Comment by Learus** [comment]
Hello there.
There already is a cleanup method. I'm using `componentWillUnmount()` to stop any intervals and autoplay functions.

To give you more information, I'm using a setTimeout on each `next()` and `prev()` (on each change), in order to correctly animate the carousel. So, basically the state change call is delayed by a certain amount of milliseconds every time the carousel changes.

My guess is, that **sometimes**, the carousel unmounts while the state change is waiting to be called (the timeout has not yet ended). So, basically that's "intended" behavior.

Maybe in the future, I will remove those timeouts, since it's not the most elegant solution that exists. It just works well for now and I have not thought of a better solution.

Check this [issue](https://github.com/Learus/react-material-ui-carousel/issues/20) to understand the reasons behind this implementation decision.

**Comment by aurimasniekis** [comment]
Adding property like `this.unmounting = false` in constructor and setting `this.unmounting = true` in `componentWillUnmount` and checking if `this.unmounting === true` in overriden `setState` before calling super setState fixed this issue for me.

**Comment by Learus** [comment]
Fixed in [version 3](https://www.npmjs.com/package/react-material-ui-carousel/v/3.0.2).

**Comment by yukihirop** [comment]
If you are using [v2](https://github.com/Learus/react-material-ui-carousel/tree/version2), apply the following patch to solve it. 

First, yarn add [postinstall-postinstall](https://github.com/ds300/postinstall-postinstall) and  [patch-package](https://github.com/ds300/patch-package).
Then write the following in your `package.json`:

```json
{
   "scripts": {
       "postinstall": "patch-package"
   }
}
```

After that, you can apply the following patch.

```diff
diff --git a/node_modules/react-material-ui-carousel/dist/components/Carousel.js b/node_modules/react-material-ui-carousel/dist/components/Carousel.js
index 979ae31..9b6a53f 100644
--- a/node_modules/react-material-ui-carousel/dist/components/Carousel.js
+++ b/node_modules/react-material-ui-carousel/dist/components/Carousel.js
@@ -204,6 +204,7 @@ var Carousel = function (_Component) {
         };
 
         _this.timer = null;
+        _this.timerAboutSetActive = null;
         return _this;
     }
 
@@ -222,6 +223,10 @@ var Carousel = function (_Component) {
         key: 'componentWillUnmount',
         value: function componentWillUnmount() {
             this.stop();
+            if (this.timerAboutSetActive) {
+                clearTimeout(this.timerAboutSetActive);
+                this.timerAboutSetActive = null;
+            }
         }
     }, {
         key: 'componentDidUpdate',
@@ -309,7 +314,7 @@ var Carousel = function (_Component) {
                 displayed: prevActive
             }, this.reset);
 
-            setTimeout(function () {
+            this.timerAboutSetActive = setTimeout(function () {
                 _this2.setState({
                     displayed: index
                 }, function () {
```
