### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ridbay** [Learus/react-material-ui-carousel#49]
Hi, This is a great work, well done.

Please how do you make the eBay™ style example, I need to make something like that, But the documentation isn't clear on how to.
Could you please give some hints.

Regards

**Comment by Learus** [comment]
Hello.
Check [this .js file](https://github.com/Learus/react-material-ui-carousel/blob/master/demo/src/components/Example.js) and [this .css file](https://github.com/Learus/react-material-ui-carousel/blob/master/demo/src/style/Example.scss). They exist in the demo directory. 
More specifically, check the implementation of the `Banner` component for the eBay styling. In order to understand how to use it with the carousel, check the `BannerExample` component, just ignore the `toggle`s and any `FormControl`s. These are used to interactively customize the carousel for demonstration purposes.

**Comment by ridbay** [comment]
Thanks
