### ISSUE TITLE
Why not save the sanitized props in the component state instead of calling the function every time it is needed?

### ISSUE THREAD

**Issue by the5ereneRebe1** [Learus/react-material-ui-carousel#59]
I can see that you are calling the sanitizeProps function every time you need the props , why not save it in a global const variable the first time, or in the state object.

**Comment by Learus** [comment]
That's what I used to do. But I had several problems with that approach.

Firstly, the component was not updating the way I wanted it to update, or how it should update.
For that reason, I had to introduce unwanted lifecycle logic (getDerivedStateFromProps, componentDidUpdate), that only complicated the implementation.

Secondly, I believe that the props which are used to customize the component should not be a part of the state. 
In my view, props are constant values given by the user, while the state is a component defined tool, used to fulfill the component's dynamic functionality.

I thought of storing the sanitized props somewhere, to save complexity, but I thought it would go against (or at least not in favor of) the react way of things. Also, it is not a very complex function. It just translates an object with optional properties into a verbose and usable set of properties. If I didn't have that function, I would have to sanitize the props "by hand" each time I wanted to use them (which is just more code for me to maintain).

In any case, I might make it a little more efficient. For example, I could make it only sanitize specific props instead of sanitizing everything.
