### ISSUE TITLE
Flickering occurs when transitioning

### ISSUE THREAD

**Issue by Yangeok** [Learus/react-material-ui-carousel#63]
Thank you very much for providing a good library. 

A problem occurred while using carousel. Using this library with **nextjs**. Looking at the network tab, requests a static image whenever makes a transition. There is no flickering when switches after completing a cycle of carousel, but there is flickering when at first time requests an image. I don't understand why there's flickering on my project during there's no flickering on the demo page. 

I'd really appreciate your help.

**Comment by Learus** [comment]
Hello and thanks for your kind words.
I don't believe this has something to do with the carousel. Rather, it has to do with your specific use of it. If the server that serves your image is slow, then there will be "flickering".
The reason why there is no flickering after the first load is that the browser probably caches data to make loading faster.
Also, the demo is created with Create-React-App, so there might be some differences with next.js. Unfortunately, I have no experience with next.js, in order to help further.

Any assistance is appreciated

**Comment by Yangeok** [comment]
I think I should go to the nextjs repository and leave an issue. Flikering occurred only when requesting static images, and flikering did not occur when requesting external images. The status code was **304 Not Modified** when flikering occurred, and **200 OK** was displayed if not.

Could you tell me if I can develop this kind of feature? Assuming that there are four images, is there any technique for calling the first image and calling the second image at the same time? If does so, the second image has already been called, so the image transition will not likely cause flickering.

**Comment by Learus** [comment]
I think you should open an issue there, or research it a bit more generally.
As for your second question, I don't think it's something that should be talked about here. You're better off asking that question in a general forum, like stackoverflow or something similar.

**Comment by Yangeok** [comment]
Thank you for your answer. I'll close this issue. Later I create PR if find usage with nextjs :)
