### ISSUE TITLE
disable initial animation / `timeout` bug?

### ISSUE THREAD

**Issue by michaeltnguyen** [Learus/react-material-ui-carousel#65]
Hi.  Thank you for making this library available!

I am using a 'slide' animation, but this causes the initial item in the carousel to slide in.  I would like the first item to just appear, and then use slide animations for transitions.

According to the documentation, I can specify `timeout={{appear: 0, enter: 500, exit: 500}}`, but this does not appear to have any effect.  Only `timeout.enter` seems to matter, but I don't see where the other values are used at all in the source.

Do you have any ideas, or can you nudge me in the right direction?  Thanks.

**Comment by Learus** [comment]
Hello there.
The animations I'm using come directly from Material UI. Specifically [Fade](https://material-ui.com/api/fade/) and [Slide](https://material-ui.com/api/slide/), so if you want more specific information about them, read up their documentation.

The reason why you don't see the values used at all in the source is that I'm giving the whole `timeout` object as props to the animations, and not specific values.

Other than that, the fact that `appear: 0` does nothing is indeed weird. I'll look more into it.

**Comment by Learus** [comment]
Hello again, and sorry for the really late response.

Turns out, there was a significant bug regarding this issue. Apparently, it was not working correctly, if the `timeout` prop was not a `number`. It should work as intended from v2.1.2 onwards. Also, please refer to the [Material UI Transition Documentation](https://material-ui.com/components/transitions/) if you have further inquiries.

Thanks for helping!

**Comment by michaeltnguyen** [comment]
Awesome, thank you!

**Comment by mattcasey** [comment]
Hi, is it OK to post on a closed PR?

This seems to still be an issue when using `^2.3.7-mui5`. I wonder if maybe the props changed since v4? There are now separate `appear` and `in` attributes, I can't tell if they existed before or not.
