### ISSUE TITLE
props interval has no effect

### ISSUE THREAD

**Issue by Eyal2062** [Learus/react-material-ui-carousel#72]
The props interval has no effect on the effect length, it is hard coded to 4000ms.  In addition in the examples there a prop named timer which is not mentioned in readme.

Thanks
Eyal

**Comment by Learus** [comment]
Hello Eyal. First of all, the interval does not define the "effect length", which I assume you mean animation duration. As the documentation says
>Defines the interval in ms between active child changes (autoPlay)

That means, that if `autoPlay` is true, then the children displayed changes every `interval` milliseconds. So in the default case every 4 seconds. Also, no, it is not hard-coded to 4000ms, as you can see in the `sanitizeProps` function in the `Carousel.js` file.
```js
const sanitizeProps = (props) =>
{
    const animation = props.animation !== undefined ? props.animation: "fade";
    const timeout = props.timeout !== undefined ? props.timeout : (animation === "fade" ? 500 : 200);

    return {
        children: props.children ? props.children : [],
        index: props.index !== undefined ? props.index : 0,
        strictIndexing: props.strictIndexing !== undefined ? props.strictIndexing : true,
        autoPlay: props.autoPlay !== undefined ? props.autoPlay : true,
-->     interval: props.interval !== undefined ? props.interval : 4000,
        indicators: props.indicators !== undefined ? props.indicators : true,
        navButtonsAlwaysInvisible: props.navButtonsAlwaysInvisible !== undefined ? props.navButtonsAlwaysInvisible : false,
        navButtonsAlwaysVisible: props.navButtonsAlwaysVisible !== undefined ? props.navButtonsAlwaysVisible : false,
        animation: animation,
        timeout: timeout,
        fullHeightHover: props.fullHeightHover !== undefined ? props.fullHeightHover : true,
        indicatorContainerProps: props.indicatorContainerProps,
        indicatorProps: props.indicatorProps,
        activeIndicatorProps: props.activeIndicatorProps,
        onChange: props.onChange !== undefined ? props.onChange : () => {},
        changeOnFirstRender: props.changeOnFirstRender !== undefined ? props.changeOnFirstRender : false,
        next: props.next !== undefined ? props.next : () => {},
        prev: props.prev !== undefined ? props.prev : () => {},
        className: props.className !== undefined ? props.className : ""
    }
}
```
It just sets the `interval` to 4000ms if the user has not specified a value. The prop you're probably looking for is the `timeout` prop. As the documentation says:
> Defines the duration of the animation

Secondly, you're right, there is no `timer` prop. I shall remove it from the demo example code since it doesn't do anything anyway.

**Comment by Learus** [comment]
Removed the obsolete code I'm referring to.
