### ISSUE TITLE
[Feature Request] upgrade react-swipable to 6.x

### ISSUE THREAD

**Issue by dohomi** [Learus/react-material-ui-carousel#93]
Hello

I'd like to suggest to upgrade to the latest version of react-swipable. Maybe it make even sense to keep it as peerDependency which would introduce a breaking change but might be more flexible for further use of its functionality

Cheers

**Comment by Learus** [comment]
Hello @dohomi and sorry for the late response.

I've updated `react-swipable` to version `v6.1.0`. I don't think I should add `react-swipeable` as a peerDependency, because I believe it would complicate the *out-of-the-box* experience I'm trying to achieve with this library.

I think it's very different from `@material-ui/core` or `@material-ui/icons` since those are far more encompassing packages and are what this package is made with. In any case thank you for your suggestion.
